LABELS_LIST = [
        "a", "i", "v", "se", "na", "že", "co", "ten", "by", "s", "z", "do", "ale", "k", "za", "o", "pro", "jako", "u", "po", "jen", "tak", "už", "nebo", "on", "být", "mít", "rok", "člověk", "práce", "ruka", "oko", "hlava", "jít", "vidět", "chtít", "vědět", "stát", "dát", "moct", "nový", "velký", "dobrý", "jiný", "starý", "český", "můj", "tvůj", "náš", "váš", "tam", "kde", "kdy", "jak", "pod", "před", "mezi", "přes", "při", "aby", "pak", "tenhle", "všechno", "každý", "den", "moc", "čas", "místo", "cesta", "voda", "země", "dům", "okno", "dveře", "stůl", "kniha", "slovo", "jméno", "otázka", "odpověď", "svět", "stát", "město", "ulice", "auta", "škola", "hra", "peníze", "život", "smrt", "láska", "strach", "radost", "smích", "pláč", "přítel", "nepřítel", "otec",
        "matka", "syn", "dcera", "bratr", "sestra", "muž", "žena", "dítě", "tělo", "srdce", "krev", "duše", "mysl", "pravda", "lež", "příliš", "žluťoučký", "kůň", "úpěl", "ďábelské", "ódy", "včelí", "plástev", "šťastný", "louže", "mříž", "déšť", "sníh", "vítr", "říčka", "řečiště", "včelař", "pouště", "dýně", "prázdniny", "hříbě", "vězeň", "kůže", "sůl", "pepř", "čaj", "káva", "loď", "moře", "mrak", "bouře", "slunce", "měsíc", "hvězda", "nebe", "tráva", "strom", "květ", "les", "hora", "pole", "řeka", "jezero", "ryba", "pták", "pes", "kočka", "pomeranč", "jablko", "banán", "citrón", "jahoda", "hruška", "švestka", "malina", "borůvka", "mrkev", "brambor", "cibule", "česnek", "chleba", "máslo", "mléko", "vejce", "sýr", "maso", "cukr", "mouka", "rýže", "těstoviny", "polévka", "oběd", "večeře", "snídaně", "pivo", "víno", "voda", "ruka", "noha", "prst", "ucho", "pusa", "nos",
        "červená", "modrá", "zelená", "žlutá", "bílá", "černá", "šedá", "hnědá", "oranžová", "fialová", "růžová", "světlo", "tma", "teplo", "chlad", "zima", "jaro", "léto", "podzim", "pondělí", "úterý", "středa", "čtvrtek", "pátek", "sobota", "neděle", "leden", "únor", "březen", "duben", "květen", "červen", "červenec", "srpen", "září", "říjen", "listopad", "prosinec", "dnes", "zítra", "včera", "teď", "potom", "brzy", "pozdě", "vždycky", "nikdy", "často", "občas", "stále", "možná", "asi", "určitě", "snad", "opravdu", "venku", "uvnitř", "nahoře", "dole", "vlevo", "vpravo", "daleko", "blízko", "široký", "úzký", "vysoký", "nízký", "dlouhý", "krátký", "rychlý", "pomalý", "těžký", "lehký", "silný", "slabý", "velký", "malý", "nový", "starý", "krásný", "ošklivý", "dobrý", "špatný", "veselý", "smutný", "bohatý", "chudý", "mladý", "starý", "chytrý", "hloupý", "čistý", "špinavý", "drahý", "levný", "plný", "prázdný", "tichý",
        "jedna", "dva", "tři", "čtyři", "pět", "šest", "sedm", "osm", "devět", "deset", "nula", "první", "druhý", "třetí", "stý", "tisící", "mnoho", "málo", "víc", "míň", "všichni", "nikdo", "někdo", "něco", "nic", "všude", "nikde", "někde", "vždy", "nikdy", "někdy", "automatizace", "inteligence", "programování", "rukopis", "generování", "architektura", "odpoledne", "včerejšek", "budoucnost", "společnost", "příležitost", "neuvěřitelný", "fantastický", "nebezpečí", "vzdělání", "zkušenost", "vteřina", "okamžik", "nálada", "počasí", "doprava", "kuchyně", "zahrada", "počítač", "telefon", "obrazovka", "klávesnice", "internet", "signál", "projekt", "úspěch", "chyba", "oprava", "pokus", "výsledek", "stavba", "město", "vesnice", "ostrov", "hora", "les", "louka", "zahrada", "květina", "strom", "zvíře", "člověk", "přítel", "rodina", "práce", "škola", "volno", "zábava", "sport", "hudba", "film", "kniha", "obraz", "barva", "zvuk", "nápad", "myšlenka", "sen", "spánek", "cesta", "cíl", "konec",
        "A", "B", "C", "Č", "D", "Ď", "E", "F", "G", "H", "CH", "I", "J", "K", "L", "M", "N", "Ň", "O", "P", "Q", "R", "Ř", "S", "Š", "T", "Ť", "U", "V", "W", "X", "Y", "Z", "Ž", "?", "!", ".", ",", ":", ";", "\"", "(", ")", "-", "/", "+", "=", "%", "@", "Brno", "Praha", "Ostrava", "Plzeň", "Labe", "Vltava", "Evropa", "Pondělí", "Únor", "Březen", "Duben", "Květen", "Červen", "Srpen", "Pan", "Paní", "Jméno", "Město", "Stát", "Škola", "Práce", "ANO", "Ne", "kdo", "Co", "Jak", "Kde", "Kdy", "Proč", "Protože", "Pokud", "Nebo", "Ale", "Takže", "Možná", "Dobrý", "Velký", "Nový", "Starý", "Český", "Malý", "První", "Leden", "úterý", "Středa", "Čtvrtek", "Pátek", "Sobota", "Neděle",
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "100", "1000", "Kč", "€", "$", "&", "#", "X", "<", ">", "Cože?", "Pozor!", "Aha...", "\"Ahoj\"", "(vždy)", "50%", "@seznam", "řidič", "dýně", "včela", "hříbě", "kůže", "sůl", "pepř", "tečka", "čárka", "otazník", "vykřičník", "závorka", "uvozovky", "pomlčka", "ABC", "DEF", "GHI", "JKL", "MNO", "PQR", "STU", "VWX", "YZ", "čřšž", "áéíóú", "ůý", "ĎŤŇ", "Ch", "Koupit", "Prodat", "Platit", "Peníze", "Účet", "Banka", "Karta", "Česko", "Slovensko", "Polsko", "Německo", "Rakousko", "Itálie", "Francie", "slunce", "Měsíc", "Hvězdy", "Vesmír", "Země", "svět", "život", "Máma", "Táta", "Děda", "Babi", "Rodina", "Štěstí", "Láska", "Kniha", "Papír", "Tužka", "Pero", "Sešit", "Počítač", "Mobil", "start", "Cíl", "Konec", "Opakovat", "Znova", "Celkem", "Hotovo"
]

chars = set()
for word in LABELS_LIST:
    for c in word:
        chars.add(c)

CHAR_MAP = { "<PAD>": 0, "<UNK>": 1, " ": 2 }
idx = 3
for c in sorted(list(chars)):
    CHAR_MAP[c] = idx
    idx += 1

VOCAB_SIZE = len(CHAR_MAP)

def encode_text(text):
    return [CHAR_MAP.get(c, 1) for c in text]
